// Generated by LiveScript 1.5.0
var http, livescript, fs, ref$, map, filter, lines, unwords, xml, xml__init, i$, len$, tag, include, template, bootstrap, jquery, page, join$ = [].join, this$ = this;
http = require('http');
livescript = require('livescript');
fs = require('fs');
ref$ = require('prelude-ls'), map = ref$.map, filter = ref$.filter, lines = ref$.lines, unwords = ref$.unwords;
xml = function(o){
  var this$ = this;
  o == null && (o = {
    tag: 'div',
    self: false
  });
  return function(opts){
    var inner, res$, i$, to$, i;
    res$ = [];
    for (i$ = 1, to$ = arguments.length; i$ < to$; ++i$) {
      res$.push(arguments[i$]);
    }
    inner = res$;
    switch (false) {
    case !(!o.self * (opts != null ? opts.length : void 8)):
      return "<" + o.tag + ">" + opts + " " + join$.call(inner, ' ') + "</" + o.tag + ">";
    case !(!o.self * !(opts != null && opts.length)):
      return '<' + o.tag + (function(){
        var results$ = [];
        for (i in opts) {
          results$.push(" " + i + "=\"" + opts[i] + "\"");
        }
        return results$;
      }()) + (">" + join$.call(inner, ' ') + "</" + o.tag + ">");
    default:
      return '<' + o.tag + (function(){
        var results$ = [];
        for (i in opts) {
          results$.push(" " + i + "=\"" + opts[i] + "\"");
        }
        return results$;
      }()) + '/>';
    }
  };
};
xml__init = function(self){
  return function(tag){
    return global[tag] = xml({
      tag: tag,
      self: self
    });
  };
};
for (i$ = 0, len$ = (ref$ = ['div', 'span', 'a', 'p', 'h4', 'h3', 'h2', 'h1', 'button', 'table', 'thead', 'tr', 'th', 'tbody', 'td', 'small', 'ul', 'ol', 'li', 'span', 'label', 'select', 'option', 'textarea', 'form', 'output', 'i', 'sub', 'time', 'section', 'html', 'head', 'body', 'title', 'script', 'footer', 'header', 'article', 'link', 'nav', 'figure', 'figcaption', 'tfoot', 'video', 'source', 'type', 'iframe']).length; i$ < len$; ++i$) {
  tag = ref$[i$];
  xml__init(false)(tag);
}
for (i$ = 0, len$ = (ref$ = ['input', 'link', 'img', 'meta', 'source', 'br', 'hr']).length; i$ < len$; ++i$) {
  tag = ref$[i$];
  xml__init(true)(tag);
}
include = function(){
  var filename, res$, i$, to$;
  res$ = [];
  for (i$ = 0, to$ = arguments.length; i$ < to$; ++i$) {
    res$.push(arguments[i$]);
  }
  filename = res$;
  return livescript.compile(fs.readFileSync(filename + ".ls", 'utf8', function(err, data){
    if (err) {
      throw err;
    } else {
      return data;
    }
  }), {
    bare: true,
    header: false
  });
};
template = function(){
  var filename, res$, i$, to$;
  res$ = [];
  for (i$ = 0, to$ = arguments.length; i$ < to$; ++i$) {
    res$.push(arguments[i$]);
  }
  filename = res$;
  return eval(livescript.compile(fs.readFileSync(filename + ".ls", 'utf8', function(err, data){
    if (err) {
      throw err;
    } else {
      return data;
    }
  }), {
    bare: true,
    header: false
  }));
};
bootstrap = link({
  rel: 'stylesheet',
  href: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css',
  integrity: 'sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi',
  crossorigin: 'anonymous'
}) + script({
  src: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js',
  integrity: 'sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK',
  crossorigin: 'anonymous'
});
jquery = script({
  src: 'https://code.jquery.com/jquery-3.1.1.min.js'
});
page = html('<!--xml__livescript-->', head(bootstrap + jquery), script(include('client')), body(div({
  'class': 'container'
}, h2('Заголовок второго уровня'), p('Текст о всякой всячине'))));
http.createServer(function(request, response){
  var x$;
  x$ = response;
  x$.writeHead(200, {
    'Content-type': 'text-html'
  });
  x$.write(String(template('bootstrap__example')));
  x$.end();
}).listen(4000);